#!/bin/bash
#
# This is an example of a deterministic script that can be generated by an agent.
# The agent's role is to produce this reliable code, then execute it.

set -euo pipefail

DATABASE_URL="$1"
ACTION="$2"

if [ -z "$DATABASE_URL" ] || [ -z "$ACTION" ]; then
  echo "Usage: $0 <database_url> <action>"
  exit 1
fi

echo "Connecting to $DATABASE_URL to perform action: $ACTION"

# In a real scenario, this would execute a command like:
# psql "$DATABASE_URL" -c "ALTER TABLE users ADD COLUMN created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();"

echo "Action '$ACTION' completed successfully."
exit 0